# Generated by Django 4.0.6 on 2022-08-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone_no', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
